eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8886
spring:
  application:
    name: qudao-member
  datasource:
          name: mysql_test
          #-------------- start ----------------# (1)
          master:
            #基本属性--注意，这里的为【jdbcurl】-- 默认使用HikariPool作为数据库连接池
            jdbcurl: jdbc:mysql://localhost:3306/new_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: 1234
            driver-class-name: com.mysql.jdbc.Driver
          slave:
            #基本属性--注意，这里为 【url】-- 使用 druid 作为数据库连接池
#            url: jdbc:mysql://47.98.55.127:3306/dev_new?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
            url: jdbc:mysql://localhost:3306/new_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: 1234
            driver-class-name: com.mysql.jdbc.Driver
          read: get,select,count,list,query,find
          write: add,create,update,delete,remove,insert
          #-------------- end ----------------#
          #druid相关配置
          druid:
            #监控统计拦截的filters
            filters: stat,wall
            #配置初始化大小/最小/最大
            initial-size: 1
            min-idle: 1
            max-active: 20
            #获取连接等待超时时间
            max-wait: 60000
            #间隔多久进行一次检测，检测需要关闭的空闲连接
            time-between-eviction-runs-millis: 60000
            #一个连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: 20
    #redis配置
  redis:
        host: 127.0.0.1
        port: 6379
        jedis:
          pool:
            max-active: 8
            max-idle: 500
            max-wait: -1
            min-idle: 0
        database: 0
#    #activeMQ配置
#    activemq:
#      broker-url: tcp://localhost:61616
#      user: admin
#      password: admin
#      pool:
#        enabled: true
#        max-connections: 50
#        expiry-timeout: 10000
#        idle-timeout: 30000
mapper:
    config-location: /mapper/*.xml
fegin:
  threadpool:
    default:
      coreSize: 10 #并发执行的最大线程数，默认10
  command:
    paas-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #命令执行超时时间，默认1000m
  #开启hystrix配置
  hystrix:
    enabled: true
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 50000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 50000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
pay:
  pay-notify_url: http://xxx/qudao-member/saas/wxpay/pay_notify.do
  qrcode-url: http://xxx/waiter-login?activityCode=
